spring.application.name=spring-demo-170
# PostgreSQL Verilənlər Bazasına Qoşulma Tənzimləmələri
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Feride
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Tənzimləmələri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect